// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Aijob
{
    public Guid JobId { get; set; }

    public int VersionId { get; set; }

    public int UserId { get; set; }

    public string Status { get; set; }

    public double? Progress { get; set; }

    public DateTime? StartedAt { get; set; }

    public DateTime? FinishedAt { get; set; }

    public int? ResultReportId { get; set; }

    public string ErrorMessage { get; set; }

    public virtual User User { get; set; }

    public virtual ChapterVersion Version { get; set; }
}