// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class AnalysisReport
{
    public int ReportId { get; set; }

    public int? VersionId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public double? OverallScore { get; set; }

    public double? PacingScore { get; set; }

    public double? EmotionScore { get; set; }

    public double? CharacterScore { get; set; }

    public string AnalysisDataJson { get; set; }

    public string GeneralFeedback { get; set; }

    public virtual ICollection<ImprovementSuggestion> ImprovementSuggestions { get; set; } = new List<ImprovementSuggestion>();

    public virtual ManuscriptVersion Version { get; set; }
}