// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Chapter
{
    public int ChapterId { get; set; }

    public int PublicationId { get; set; }

    public int ChapterNo { get; set; }

    public string Title { get; set; }

    public string ContentRef { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Publication Publication { get; set; }
}