// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class ChapterVersion
{
    public int VersionId { get; set; }

    public int ChapterId { get; set; }

    public int VersionNumber { get; set; }

    public string RawContent { get; set; }

    public int? WordCount { get; set; }

    public DateTime? UploadDate { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<Aijob> Aijobs { get; set; } = new List<Aijob>();

    public virtual ICollection<AnalysisReport> AnalysisReports { get; set; } = new List<AnalysisReport>();

    public virtual Chapter Chapter { get; set; }

    public virtual ICollection<ManuscriptChunk> ManuscriptChunks { get; set; } = new List<ManuscriptChunk>();
}