// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class ChatMessage
{
    public long MessageId { get; set; }

    public int SessionId { get; set; }

    public string Sender { get; set; }

    public string Content { get; set; }

    public string ReferenceChunkIds { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ChatSession Session { get; set; }
}