// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class ChatSession
{
    public int SessionId { get; set; }

    public int UserId { get; set; }

    public int? ProjectId { get; set; }

    public string Title { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<ChatMessage> ChatMessages { get; set; } = new List<ChatMessage>();

    public virtual Project Project { get; set; }

    public virtual User User { get; set; }
}