// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Flag
{
    public int FlagId { get; set; }

    public int ReporterId { get; set; }

    public string TargetType { get; set; }

    public int TargetId { get; set; }

    public string Reason { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? ResolvedAt { get; set; }

    public int? ResolvedBy { get; set; }

    public virtual User Reporter { get; set; }

    public virtual User ResolvedByNavigation { get; set; }
}