// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Follow
{
    public int FollowId { get; set; }

    public int FollowerId { get; set; }

    public int AuthorId { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual User Author { get; set; }

    public virtual User Follower { get; set; }
}