// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Genre
{
    public int GenreId { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Project> Projects { get; set; } = new List<Project>();
}