// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class ImprovementSuggestion
{
    public int SuggestionId { get; set; }

    public int? ReportId { get; set; }

    public string SuggestionType { get; set; }

    public string OriginalText { get; set; }

    public string SuggestionText { get; set; }

    public string Severity { get; set; }

    public DateTime? CreatedAt { get; set; }

    public int? CreatorId { get; set; }

    public bool? IsResolved { get; set; }

    public virtual User Creator { get; set; }

    public virtual AnalysisReport Report { get; set; }
}