// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class ManuscriptVersion
{
    public int VersionId { get; set; }

    public int? ProjectId { get; set; }

    public int VersionNumber { get; set; }

    public string Title { get; set; }

    public string FilePath { get; set; }

    public string RawContent { get; set; }

    public int? WordCount { get; set; }

    public DateTime? UploadDate { get; set; }

    public bool? IsPublished { get; set; }

    public virtual ICollection<AnalysisReport> AnalysisReports { get; set; } = new List<AnalysisReport>();

    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    public virtual ICollection<ManuscriptChunk> ManuscriptChunks { get; set; } = new List<ManuscriptChunk>();

    public virtual Project Project { get; set; }

    public virtual ICollection<Publication> Publications { get; set; } = new List<Publication>();
}