// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class ManuscriptChunk
{
    public int ChunkId { get; set; }

    public int? VersionId { get; set; }

    public int? ChunkIndex { get; set; }

    public string ContentText { get; set; }

    public string VectorId { get; set; }

    public virtual ChapterVersion Version { get; set; }
}