// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Payment
{
    public long PaymentId { get; set; }

    public int SubscriptionId { get; set; }

    public decimal Amount { get; set; }

    public string Currency { get; set; }

    public string Provider { get; set; }

    public string ProviderTxnId { get; set; }

    public string Status { get; set; }

    public DateTime? PaidAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual UserSubscription Subscription { get; set; }
}