// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Publication
{
    public int PublicationId { get; set; }

    public int ProjectId { get; set; }

    public int VersionId { get; set; }

    public DateTime PublishedAt { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<Chapter> Chapters { get; set; } = new List<Chapter>();

    public virtual Project Project { get; set; }

    public virtual ManuscriptVersion Version { get; set; }
}