// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Rating
{
    public int RatingId { get; set; }

    public int UserId { get; set; }

    public int ProjectId { get; set; }

    public int Score { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Project Project { get; set; }

    public virtual User User { get; set; }
}