// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class ReadingHistory
{
    public int HistoryId { get; set; }

    public int? UserId { get; set; }

    public int? ProjectId { get; set; }

    public int? LastVersionId { get; set; }

    public int? LastChunkIndex { get; set; }

    public DateTime? LastReadTime { get; set; }

    public virtual Project Project { get; set; }

    public virtual User User { get; set; }
}