// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class StaffAuthorContact
{
    public int ContactId { get; set; }

    public int? StaffId { get; set; }

    public int? AuthorId { get; set; }

    public DateTime? ContactDate { get; set; }

    public string Status { get; set; }

    public virtual User Author { get; set; }

    public virtual User Staff { get; set; }

    public virtual ICollection<StaffAuthorMessage> StaffAuthorMessages { get; set; } = new List<StaffAuthorMessage>();
}