// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class StaffAuthorMessage
{
    public int MessageId { get; set; }

    public int? ContactId { get; set; }

    public string SenderType { get; set; }

    public int? SenderId { get; set; }

    public string MessageText { get; set; }

    public DateTime? SendAt { get; set; }

    public bool? IsRead { get; set; }

    public virtual StaffAuthorContact Contact { get; set; }

    public virtual User Sender { get; set; }
}