// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class SubscriptionPlan
{
    public int PlanId { get; set; }

    public string PlanName { get; set; }

    public decimal Price { get; set; }

    public int? AnalysisLimit { get; set; }

    public bool? CanReadUnlimited { get; set; }

    public string Description { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<UserSubscription> UserSubscriptions { get; set; } = new List<UserSubscription>();
}