// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class SystemConfig
{
    public string ConfigKey { get; set; }

    public string ConfigValue { get; set; }

    public int? LastUpdatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual User LastUpdatedByNavigation { get; set; }
}