// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class UserLibrary
{
    public int LibraryId { get; set; }

    public int? UserId { get; set; }

    public int? ProjectId { get; set; }

    public string Status { get; set; }

    public DateTime? LastAccessDate { get; set; }

    public virtual Project Project { get; set; }

    public virtual User User { get; set; }
}