// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class StoryAI_DBContext : DbContext
{
    public StoryAI_DBContext()
    {
    }

    public StoryAI_DBContext(DbContextOptions<StoryAI_DBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AnalysisReport> AnalysisReports { get; set; }

    public virtual DbSet<Chapter> Chapters { get; set; }

    public virtual DbSet<Comment> Comments { get; set; }

    public virtual DbSet<Flag> Flags { get; set; }

    public virtual DbSet<Follow> Follows { get; set; }

    public virtual DbSet<ImprovementSuggestion> ImprovementSuggestions { get; set; }

    public virtual DbSet<ManuscriptChunk> ManuscriptChunks { get; set; }

    public virtual DbSet<ManuscriptVersion> ManuscriptVersions { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<Project> Projects { get; set; }

    public virtual DbSet<Publication> Publications { get; set; }

    public virtual DbSet<Rating> Ratings { get; set; }

    public virtual DbSet<ReadingHistory> ReadingHistories { get; set; }

    public virtual DbSet<SubscriptionPlan> SubscriptionPlans { get; set; }

    public virtual DbSet<SystemConfig> SystemConfigs { get; set; }

    public virtual DbSet<SystemLog> SystemLogs { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserLibrary> UserLibraries { get; set; }

    public virtual DbSet<UserSubscription> UserSubscriptions { get; set; }

//    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
//#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
//        => optionsBuilder.UseSqlServer("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=StoryAI_DB;User ID=hihi;Password=123456");
    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("appsettings.json")
            .Build();

        string connectionString = config.GetConnectionString(connectionStringName);
        return connectionString;
    }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(GetConnectionString("DefaultConnection")).UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AnalysisReport>(entity =>
        {
            entity.HasKey(e => e.ReportId).HasName("PK__Analysis__D5BD48E5E2901892");

            entity.HasIndex(e => e.VersionId, "IX_AnalysisReports_Version");

            entity.Property(e => e.ReportId).HasColumnName("ReportID");
            entity.Property(e => e.AnalysisDataJson).HasColumnName("AnalysisDataJSON");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.VersionId).HasColumnName("VersionID");

            entity.HasOne(d => d.Version).WithMany(p => p.AnalysisReports)
                .HasForeignKey(d => d.VersionId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__AnalysisR__Versi__5441852A");
        });

        modelBuilder.Entity<Chapter>(entity =>
        {
            entity.HasKey(e => e.ChapterId).HasName("PK__Chapters__0893A34A207B002F");

            entity.HasIndex(e => new { e.PublicationId, e.ChapterNo }, "IX_Chapters_Pub_No");

            entity.HasIndex(e => new { e.PublicationId, e.ChapterNo }, "UQ_Pub_Chapter").IsUnique();

            entity.Property(e => e.ChapterId).HasColumnName("ChapterID");
            entity.Property(e => e.ContentRef).HasMaxLength(500);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.PublicationId).HasColumnName("PublicationID");
            entity.Property(e => e.Title).HasMaxLength(255);
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(sysutcdatetime())");

            entity.HasOne(d => d.Publication).WithMany(p => p.Chapters)
                .HasForeignKey(d => d.PublicationId)
                .HasConstraintName("FK__Chapters__Public__4F7CD00D");
        });

        modelBuilder.Entity<Comment>(entity =>
        {
            entity.HasKey(e => e.CommentId).HasName("PK__Comments__C3B4DFAA7FFF51C0");

            entity.HasIndex(e => e.ParentCommentId, "IX_Comments_Parent");

            entity.HasIndex(e => e.ProjectId, "IX_Comments_Project");

            entity.HasIndex(e => e.VersionId, "IX_Comments_Version");

            entity.Property(e => e.CommentId).HasColumnName("CommentID");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.ParentCommentId).HasColumnName("ParentCommentID");
            entity.Property(e => e.ProjectId).HasColumnName("ProjectID");
            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.VersionId).HasColumnName("VersionID");

            entity.HasOne(d => d.Project).WithMany(p => p.Comments)
                .HasForeignKey(d => d.ProjectId)
                .HasConstraintName("FK__Comments__Projec__70DDC3D8");

            entity.HasOne(d => d.User).WithMany(p => p.Comments)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__Comments__UserID__6FE99F9F");

            entity.HasOne(d => d.Version).WithMany(p => p.Comments)
                .HasForeignKey(d => d.VersionId)
                .HasConstraintName("FK__Comments__Versio__71D1E811");
        });

        modelBuilder.Entity<Flag>(entity =>
        {
            entity.HasKey(e => e.FlagId).HasName("PK__Flags__780D45B30783373D");

            entity.HasIndex(e => e.Status, "IX_Flags_Status");

            entity.Property(e => e.FlagId).HasColumnName("FlagID");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.ReporterId).HasColumnName("ReporterID");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("Pending");
            entity.Property(e => e.TargetId).HasColumnName("TargetID");
            entity.Property(e => e.TargetType)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.Reporter).WithMany(p => p.FlagReporters)
                .HasForeignKey(d => d.ReporterId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Flags__ReporterI__7D439ABD");

            entity.HasOne(d => d.ResolvedByNavigation).WithMany(p => p.FlagResolvedByNavigations)
                .HasForeignKey(d => d.ResolvedBy)
                .HasConstraintName("FK__Flags__ResolvedB__02084FDA");
        });

        modelBuilder.Entity<Follow>(entity =>
        {
            entity.HasKey(e => e.FollowId).HasName("PK__Follows__2CE8108EA6654713");

            entity.HasIndex(e => e.AuthorId, "IX_Follows_Author");

            entity.HasIndex(e => e.FollowerId, "IX_Follows_Follower");

            entity.HasIndex(e => new { e.FollowerId, e.AuthorId }, "UQ_Follow").IsUnique();

            entity.Property(e => e.FollowId).HasColumnName("FollowID");
            entity.Property(e => e.AuthorId).HasColumnName("AuthorID");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.FollowerId).HasColumnName("FollowerID");

            entity.HasOne(d => d.Author).WithMany(p => p.FollowAuthors)
                .HasForeignKey(d => d.AuthorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Follows__AuthorI__6C190EBB");

            entity.HasOne(d => d.Follower).WithMany(p => p.FollowFollowers)
                .HasForeignKey(d => d.FollowerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Follows__Followe__6B24EA82");
        });

        modelBuilder.Entity<ImprovementSuggestion>(entity =>
        {
            entity.HasKey(e => e.SuggestionId).HasName("PK__Improvem__9409952881246059");

            entity.Property(e => e.SuggestionId).HasColumnName("SuggestionID");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.ReportId).HasColumnName("ReportID");
            entity.Property(e => e.Severity)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.SuggestionType)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Report).WithMany(p => p.ImprovementSuggestions)
                .HasForeignKey(d => d.ReportId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__Improveme__Repor__5812160E");
        });

        modelBuilder.Entity<ManuscriptChunk>(entity =>
        {
            entity.HasKey(e => e.ChunkId).HasName("PK__Manuscri__FBFF9D20DBA82673");

            entity.HasIndex(e => new { e.VersionId, e.ChunkIndex }, "IX_Chunks_Version");

            entity.HasIndex(e => new { e.VersionId, e.ChunkIndex }, "UQ_Version_Chunk").IsUnique();

            entity.Property(e => e.ChunkId).HasColumnName("ChunkID");
            entity.Property(e => e.VectorId)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("VectorID");
            entity.Property(e => e.VersionId).HasColumnName("VersionID");

            entity.HasOne(d => d.Version).WithMany(p => p.ManuscriptChunks)
                .HasForeignKey(d => d.VersionId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__Manuscrip__Versi__5CD6CB2B");
        });

        modelBuilder.Entity<ManuscriptVersion>(entity =>
        {
            entity.HasKey(e => e.VersionId).HasName("PK__Manuscri__16C6402FCD8BF6B6");

            entity.HasIndex(e => new { e.ProjectId, e.VersionNumber }, "IX_Versions_ProjectVer");

            entity.HasIndex(e => new { e.ProjectId, e.VersionNumber }, "UQ_Project_Version").IsUnique();

            entity.Property(e => e.VersionId).HasColumnName("VersionID");
            entity.Property(e => e.FilePath).HasMaxLength(500);
            entity.Property(e => e.IsPublished).HasDefaultValue(false);
            entity.Property(e => e.ProjectId).HasColumnName("ProjectID");
            entity.Property(e => e.Title).HasMaxLength(200);
            entity.Property(e => e.UploadDate).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Project).WithMany(p => p.ManuscriptVersions)
                .HasForeignKey(d => d.ProjectId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__Manuscrip__Proje__440B1D61");
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.HasKey(e => e.PaymentId).HasName("PK__Payments__9B556A586FE18F97");

            entity.HasIndex(e => e.SubscriptionId, "IX_Payments_Sub");

            entity.Property(e => e.PaymentId).HasColumnName("PaymentID");
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Currency)
                .IsRequired()
                .HasMaxLength(3)
                .IsUnicode(false)
                .HasDefaultValue("VND")
                .IsFixedLength();
            entity.Property(e => e.Provider).HasMaxLength(50);
            entity.Property(e => e.ProviderTxnId)
                .HasMaxLength(255)
                .HasColumnName("ProviderTxnID");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.SubscriptionId).HasColumnName("SubscriptionID");

            entity.HasOne(d => d.Subscription).WithMany(p => p.Payments)
                .HasForeignKey(d => d.SubscriptionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Payments__Subscr__36B12243");
        });

        modelBuilder.Entity<Project>(entity =>
        {
            entity.HasKey(e => e.ProjectId).HasName("PK__Projects__761ABED0ADC79AEE");

            entity.HasIndex(e => new { e.AuthorId, e.Status }, "IX_Projects_Author_Status");

            entity.HasIndex(e => e.IsDeleted, "IX_Projects_IsDeleted");

            entity.Property(e => e.ProjectId).HasColumnName("ProjectID");
            entity.Property(e => e.AuthorId).HasColumnName("AuthorID");
            entity.Property(e => e.CoverImageUrl)
                .HasMaxLength(500)
                .HasColumnName("CoverImageURL");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Genre).HasMaxLength(50);
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("Draft");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(200);

            entity.HasOne(d => d.Author).WithMany(p => p.Projects)
                .HasForeignKey(d => d.AuthorId)
                .HasConstraintName("FK__Projects__Author__3C69FB99");
        });

        modelBuilder.Entity<Publication>(entity =>
        {
            entity.HasKey(e => e.PublicationId).HasName("PK__Publicat__05E6DC5818900D52");

            entity.HasIndex(e => e.ProjectId, "IX_Pubs_Project");

            entity.Property(e => e.PublicationId).HasColumnName("PublicationID");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.ProjectId).HasColumnName("ProjectID");
            entity.Property(e => e.PublishedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.VersionId).HasColumnName("VersionID");

            entity.HasOne(d => d.Project).WithMany(p => p.Publications)
                .HasForeignKey(d => d.ProjectId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Publicati__Proje__48CFD27E");

            entity.HasOne(d => d.Version).WithMany(p => p.Publications)
                .HasForeignKey(d => d.VersionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Publicati__Versi__49C3F6B7");
        });

        modelBuilder.Entity<Rating>(entity =>
        {
            entity.HasKey(e => e.RatingId).HasName("PK__Ratings__FCCDF85C51B75730");

            entity.HasIndex(e => e.ProjectId, "IX_Ratings_Project");

            entity.HasIndex(e => new { e.UserId, e.ProjectId }, "UQ_Rating").IsUnique();

            entity.Property(e => e.RatingId).HasColumnName("RatingID");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.ProjectId).HasColumnName("ProjectID");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Project).WithMany(p => p.Ratings)
                .HasForeignKey(d => d.ProjectId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Ratings__Project__787EE5A0");

            entity.HasOne(d => d.User).WithMany(p => p.Ratings)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Ratings__UserID__778AC167");
        });

        modelBuilder.Entity<ReadingHistory>(entity =>
        {
            entity.HasKey(e => e.HistoryId).HasName("PK__ReadingH__4D7B4ADD017433E6");

            entity.ToTable("ReadingHistory");

            entity.HasIndex(e => new { e.UserId, e.ProjectId }, "IX_ReadingHistory_UserProject");

            entity.Property(e => e.HistoryId).HasColumnName("HistoryID");
            entity.Property(e => e.LastReadTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastVersionId).HasColumnName("LastVersionID");
            entity.Property(e => e.ProjectId).HasColumnName("ProjectID");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Project).WithMany(p => p.ReadingHistories)
                .HasForeignKey(d => d.ProjectId)
                .HasConstraintName("FK__ReadingHi__Proje__66603565");

            entity.HasOne(d => d.User).WithMany(p => p.ReadingHistories)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__ReadingHi__UserI__656C112C");
        });

        modelBuilder.Entity<SubscriptionPlan>(entity =>
        {
            entity.HasKey(e => e.PlanId).HasName("PK__Subscrip__755C22D7F7DA6493");

            entity.Property(e => e.PlanId).HasColumnName("PlanID");
            entity.Property(e => e.AnalysisLimit).HasDefaultValue(5);
            entity.Property(e => e.CanReadUnlimited).HasDefaultValue(false);
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.PlanName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Price).HasColumnType("decimal(18, 2)");
        });

        modelBuilder.Entity<SystemConfig>(entity =>
        {
            entity.HasKey(e => e.ConfigKey).HasName("PK__SystemCo__4A306785EE70BAD4");

            entity.Property(e => e.ConfigKey)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ConfigValue).HasMaxLength(255);
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.LastUpdatedByNavigation).WithMany(p => p.SystemConfigs)
                .HasForeignKey(d => d.LastUpdatedBy)
                .HasConstraintName("FK__SystemCon__LastU__08B54D69");
        });

        modelBuilder.Entity<SystemLog>(entity =>
        {
            entity.HasKey(e => e.LogId).HasName("PK__SystemLo__5E5499A8B471E073");

            entity.Property(e => e.LogId).HasColumnName("LogID");
            entity.Property(e => e.ActionType)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ActorId).HasColumnName("ActorID");
            entity.Property(e => e.Timestamp).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Actor).WithMany(p => p.SystemLogs)
                .HasForeignKey(d => d.ActorId)
                .HasConstraintName("FK__SystemLog__Actor__04E4BC85");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__Users__1788CCACD24D46D1");

            entity.HasIndex(e => e.Email, "IX_Users_Email");

            entity.HasIndex(e => e.IsActive, "IX_Users_IsActive");

            entity.HasIndex(e => e.Role, "IX_Users_Role");

            entity.HasIndex(e => e.Email, "UQ__Users__A9D105341D3C6240").IsUnique();

            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.AvatarUrl)
                .HasMaxLength(500)
                .HasColumnName("AvatarURL");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Role)
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<UserLibrary>(entity =>
        {
            entity.HasKey(e => e.LibraryId).HasName("PK__UserLibr__A13647BFDA74FAD0");

            entity.ToTable("UserLibrary");

            entity.HasIndex(e => e.UserId, "IX_Library_User");

            entity.Property(e => e.LibraryId).HasColumnName("LibraryID");
            entity.Property(e => e.LastAccessDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.ProjectId).HasColumnName("ProjectID");
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .HasDefaultValue("Reading");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Project).WithMany(p => p.UserLibraries)
                .HasForeignKey(d => d.ProjectId)
                .HasConstraintName("FK__UserLibra__Proje__60A75C0F");

            entity.HasOne(d => d.User).WithMany(p => p.UserLibraries)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__UserLibra__UserI__5FB337D6");
        });

        modelBuilder.Entity<UserSubscription>(entity =>
        {
            entity.HasKey(e => e.SubscriptionId).HasName("PK__UserSubs__9A2B24BD2DCC3AD7");

            entity.HasIndex(e => new { e.UserId, e.Status }, "IX_UserSubs_User_Status");

            entity.Property(e => e.SubscriptionId).HasColumnName("SubscriptionID");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.PlanId).HasColumnName("PlanID");
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("Active");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Plan).WithMany(p => p.UserSubscriptions)
                .HasForeignKey(d => d.PlanId)
                .HasConstraintName("FK__UserSubsc__PlanI__300424B4");

            entity.HasOne(d => d.User).WithMany(p => p.UserSubscriptions)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__UserSubsc__UserI__2F10007B");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}