// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class StoryAI_DBContext : DbContext
{
    public StoryAI_DBContext()
    {
    }

    public StoryAI_DBContext(DbContextOptions<StoryAI_DBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Aijob> Aijobs { get; set; }

    public virtual DbSet<AnalysisReport> AnalysisReports { get; set; }

    public virtual DbSet<Chapter> Chapters { get; set; }

    public virtual DbSet<ChapterVersion> ChapterVersions { get; set; }

    public virtual DbSet<ChatMessage> ChatMessages { get; set; }

    public virtual DbSet<ChatSession> ChatSessions { get; set; }

    public virtual DbSet<Genre> Genres { get; set; }

    public virtual DbSet<ImprovementSuggestion> ImprovementSuggestions { get; set; }

    public virtual DbSet<ManuscriptChunk> ManuscriptChunks { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<Project> Projects { get; set; }

    public virtual DbSet<StaffAuthorContact> StaffAuthorContacts { get; set; }

    public virtual DbSet<StaffAuthorMessage> StaffAuthorMessages { get; set; }

    public virtual DbSet<SubscriptionPlan> SubscriptionPlans { get; set; }

    public virtual DbSet<SystemConfig> SystemConfigs { get; set; }

    public virtual DbSet<SystemLog> SystemLogs { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserSubscription> UserSubscriptions { get; set; }

    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("appsettings.json")
            .Build();

        string connectionString = config.GetConnectionString(connectionStringName);
        return connectionString;
    }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(GetConnectionString("DefaultConnection")).UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Aijob>(entity =>
        {
            entity.HasKey(e => e.JobId).HasName("PK__AIJobs__056690E24DAFD8B0");

            entity.ToTable("AIJobs");

            entity.HasIndex(e => e.Status, "IX_AIJobs_Status");

            entity.Property(e => e.JobId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("JobID");
            entity.Property(e => e.Progress).HasDefaultValue(0.0);
            entity.Property(e => e.ResultReportId).HasColumnName("ResultReportID");
            entity.Property(e => e.StartedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("Pending");
            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.VersionId).HasColumnName("VersionID");

            entity.HasOne(d => d.User).WithMany(p => p.Aijobs)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__AIJobs__UserID__52593CB8");

            entity.HasOne(d => d.Version).WithMany(p => p.Aijobs)
                .HasForeignKey(d => d.VersionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__AIJobs__VersionI__5165187F");
        });

        modelBuilder.Entity<AnalysisReport>(entity =>
        {
            entity.HasKey(e => e.ReportId).HasName("PK__Analysis__D5BD48E50DCBC821");

            entity.Property(e => e.ReportId).HasColumnName("ReportID");
            entity.Property(e => e.AnalysisDataJson).HasColumnName("AnalysisDataJSON");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.VersionId).HasColumnName("VersionID");

            entity.HasOne(d => d.Version).WithMany(p => p.AnalysisReports)
                .HasForeignKey(d => d.VersionId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__AnalysisR__Versi__59063A47");
        });

        modelBuilder.Entity<Chapter>(entity =>
        {
            entity.HasKey(e => e.ChapterId).HasName("PK__Chapters__0893A34A1BE48EDA");

            entity.HasIndex(e => new { e.ProjectId, e.ChapterNo }, "UQ_Project_Chapter").IsUnique();

            entity.Property(e => e.ChapterId).HasColumnName("ChapterID");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.ProjectId).HasColumnName("ProjectID");
            entity.Property(e => e.Title).HasMaxLength(255);

            entity.HasOne(d => d.Project).WithMany(p => p.Chapters)
                .HasForeignKey(d => d.ProjectId)
                .HasConstraintName("FK__Chapters__Projec__46E78A0C");
        });

        modelBuilder.Entity<ChapterVersion>(entity =>
        {
            entity.HasKey(e => e.VersionId).HasName("PK__ChapterV__16C6402FC73BA352");

            entity.HasIndex(e => new { e.ChapterId, e.VersionNumber }, "UQ_Chapter_Version").IsUnique();

            entity.Property(e => e.VersionId).HasColumnName("VersionID");
            entity.Property(e => e.ChapterId).HasColumnName("ChapterID");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.UploadDate).HasDefaultValueSql("(sysutcdatetime())");

            entity.HasOne(d => d.Chapter).WithMany(p => p.ChapterVersions)
                .HasForeignKey(d => d.ChapterId)
                .HasConstraintName("FK__ChapterVe__Chapt__4BAC3F29");
        });

        modelBuilder.Entity<ChatMessage>(entity =>
        {
            entity.HasKey(e => e.MessageId).HasName("PK__ChatMess__C87C037CAC9FBD04");

            entity.HasIndex(e => e.SessionId, "IX_ChatMessages_Session");

            entity.Property(e => e.MessageId).HasColumnName("MessageID");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.ReferenceChunkIds).HasColumnName("ReferenceChunkIDs");
            entity.Property(e => e.Sender)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.SessionId).HasColumnName("SessionID");

            entity.HasOne(d => d.Session).WithMany(p => p.ChatMessages)
                .HasForeignKey(d => d.SessionId)
                .HasConstraintName("FK__ChatMessa__Sessi__6B24EA82");
        });

        modelBuilder.Entity<ChatSession>(entity =>
        {
            entity.HasKey(e => e.SessionId).HasName("PK__ChatSess__C9F49270CEACF531");

            entity.HasIndex(e => e.ProjectId, "IX_ChatSessions_Project");

            entity.HasIndex(e => e.UserId, "IX_ChatSessions_User");

            entity.Property(e => e.SessionId).HasColumnName("SessionID");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.ProjectId).HasColumnName("ProjectID");
            entity.Property(e => e.Title).HasMaxLength(200);
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Project).WithMany(p => p.ChatSessions)
                .HasForeignKey(d => d.ProjectId)
                .HasConstraintName("FK__ChatSessi__Proje__6754599E");

            entity.HasOne(d => d.User).WithMany(p => p.ChatSessions)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ChatSessi__UserI__66603565");
        });

        modelBuilder.Entity<Genre>(entity =>
        {
            entity.HasKey(e => e.GenreId).HasName("PK__Genres__0385055EA75081B6");

            entity.HasIndex(e => e.Name, "UQ__Genres__737584F60E52E6DF").IsUnique();

            entity.Property(e => e.GenreId).HasColumnName("GenreID");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<ImprovementSuggestion>(entity =>
        {
            entity.HasKey(e => e.SuggestionId).HasName("PK__Improvem__9409952806BF588F");

            entity.Property(e => e.SuggestionId).HasColumnName("SuggestionID");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.CreatorId).HasColumnName("CreatorID");
            entity.Property(e => e.IsResolved).HasDefaultValue(false);
            entity.Property(e => e.ReportId).HasColumnName("ReportID");
            entity.Property(e => e.Severity)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.SuggestionType)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Creator).WithMany(p => p.ImprovementSuggestions)
                .HasForeignKey(d => d.CreatorId)
                .HasConstraintName("FK__Improveme__Creat__5EBF139D");

            entity.HasOne(d => d.Report).WithMany(p => p.ImprovementSuggestions)
                .HasForeignKey(d => d.ReportId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__Improveme__Repor__5CD6CB2B");
        });

        modelBuilder.Entity<ManuscriptChunk>(entity =>
        {
            entity.HasKey(e => e.ChunkId).HasName("PK__Manuscri__FBFF9D201FC20BCB");

            entity.HasIndex(e => new { e.VersionId, e.ChunkIndex }, "UQ_Version_Chunk").IsUnique();

            entity.Property(e => e.ChunkId).HasColumnName("ChunkID");
            entity.Property(e => e.VectorId)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("VectorID");
            entity.Property(e => e.VersionId).HasColumnName("VersionID");

            entity.HasOne(d => d.Version).WithMany(p => p.ManuscriptChunks)
                .HasForeignKey(d => d.VersionId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__Manuscrip__Versi__6383C8BA");
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.HasKey(e => e.PaymentId).HasName("PK__Payments__9B556A58A74C6CB1");

            entity.HasIndex(e => e.CreatedAt, "IX_Payments_Date");

            entity.HasIndex(e => e.Status, "IX_Payments_Status");

            entity.HasIndex(e => e.SubscriptionId, "IX_Payments_Sub");

            entity.Property(e => e.PaymentId).HasColumnName("PaymentID");
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Currency)
                .HasMaxLength(3)
                .IsUnicode(false)
                .HasDefaultValue("VND")
                .IsFixedLength();
            entity.Property(e => e.Note).HasMaxLength(500);
            entity.Property(e => e.Provider).HasMaxLength(50);
            entity.Property(e => e.ProviderTxnId)
                .HasMaxLength(255)
                .HasColumnName("ProviderTxnID");
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("Pending");
            entity.Property(e => e.SubscriptionId).HasColumnName("SubscriptionID");

            entity.HasOne(d => d.Subscription).WithMany(p => p.Payments)
                .HasForeignKey(d => d.SubscriptionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Payments__Subscr__778AC167");
        });

        modelBuilder.Entity<Project>(entity =>
        {
            entity.HasKey(e => e.ProjectId).HasName("PK__Projects__761ABED07DEAC88E");

            entity.Property(e => e.ProjectId).HasColumnName("ProjectID");
            entity.Property(e => e.AuthorId).HasColumnName("AuthorID");
            entity.Property(e => e.CoverImageUrl)
                .HasMaxLength(500)
                .HasColumnName("CoverImageURL");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.IsDeleted).HasDefaultValue(false);
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("Draft");

            entity.HasOne(d => d.Author).WithMany(p => p.Projects)
                .HasForeignKey(d => d.AuthorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Projects__Author__3B75D760");

            entity.HasMany(d => d.Genres).WithMany(p => p.Projects)
                .UsingEntity<Dictionary<string, object>>(
                    "ProjectGenre",
                    r => r.HasOne<Genre>().WithMany()
                        .HasForeignKey("GenreId")
                        .HasConstraintName("FK__ProjectGe__Genre__4316F928"),
                    l => l.HasOne<Project>().WithMany()
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("FK__ProjectGe__Proje__4222D4EF"),
                    j =>
                    {
                        j.HasKey("ProjectId", "GenreId");
                        j.ToTable("ProjectGenres");
                        j.IndexerProperty<int>("ProjectId").HasColumnName("ProjectID");
                        j.IndexerProperty<int>("GenreId").HasColumnName("GenreID");
                    });
        });

        modelBuilder.Entity<StaffAuthorContact>(entity =>
        {
            entity.HasKey(e => e.ContactId).HasName("PK__StaffAut__5C6625BB779563F4");

            entity.ToTable("StaffAuthorContact");

            entity.HasIndex(e => e.AuthorId, "IX_StaffAuthorContact_AuthorID");

            entity.HasIndex(e => e.StaffId, "IX_StaffAuthorContact_StaffID");

            entity.HasIndex(e => e.Status, "IX_StaffAuthorContact_Status");

            entity.Property(e => e.ContactId).HasColumnName("ContactID");
            entity.Property(e => e.AuthorId).HasColumnName("AuthorID");
            entity.Property(e => e.ContactDate).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.StaffId).HasColumnName("StaffID");
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("Active");

            entity.HasOne(d => d.Author).WithMany(p => p.StaffAuthorContactAuthors)
                .HasForeignKey(d => d.AuthorId)
                .HasConstraintName("FK_StaffAuthorContact_Author");

            entity.HasOne(d => d.Staff).WithMany(p => p.StaffAuthorContactStaffs)
                .HasForeignKey(d => d.StaffId)
                .HasConstraintName("FK_StaffAuthorContact_Staff");
        });

        modelBuilder.Entity<StaffAuthorMessage>(entity =>
        {
            entity.HasKey(e => e.MessageId).HasName("PK__StaffAut__C87C037C0CFDEA2A");

            entity.ToTable("StaffAuthorMessage");

            entity.HasIndex(e => e.ContactId, "IX_StaffAuthorMessage_ContactID");

            entity.HasIndex(e => e.IsRead, "IX_StaffAuthorMessage_IsRead");

            entity.HasIndex(e => e.SendAt, "IX_StaffAuthorMessage_SendAt");

            entity.Property(e => e.MessageId).HasColumnName("MessageID");
            entity.Property(e => e.ContactId).HasColumnName("ContactID");
            entity.Property(e => e.IsRead).HasDefaultValue(false);
            entity.Property(e => e.SendAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.SenderId).HasColumnName("SenderID");
            entity.Property(e => e.SenderType)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.Contact).WithMany(p => p.StaffAuthorMessages)
                .HasForeignKey(d => d.ContactId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_StaffAuthorMessage_Contact");

            entity.HasOne(d => d.Sender).WithMany(p => p.StaffAuthorMessages)
                .HasForeignKey(d => d.SenderId)
                .HasConstraintName("FK_StaffAuthorMessage_Sender");
        });

        modelBuilder.Entity<SubscriptionPlan>(entity =>
        {
            entity.HasKey(e => e.PlanId).HasName("PK__Subscrip__755C22D7B49FE93C");

            entity.Property(e => e.PlanId).HasColumnName("PlanID");
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.MaxAnalysisCount).HasDefaultValue(10);
            entity.Property(e => e.MaxTokenLimit).HasDefaultValue(50000L);
            entity.Property(e => e.PlanName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Price)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(18, 2)");
        });

        modelBuilder.Entity<SystemConfig>(entity =>
        {
            entity.HasKey(e => e.ConfigKey).HasName("PK__SystemCo__4A306785696A1823");

            entity.Property(e => e.ConfigKey)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ConfigValue).HasMaxLength(255);
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(sysutcdatetime())");

            entity.HasOne(d => d.LastUpdatedByNavigation).WithMany(p => p.SystemConfigs)
                .HasForeignKey(d => d.LastUpdatedBy)
                .HasConstraintName("FK__SystemCon__LastU__73BA3083");
        });

        modelBuilder.Entity<SystemLog>(entity =>
        {
            entity.HasKey(e => e.LogId).HasName("PK__SystemLo__5E5499A82447CF22");

            entity.Property(e => e.LogId).HasColumnName("LogID");
            entity.Property(e => e.ActionType)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ActorId).HasColumnName("ActorID");
            entity.Property(e => e.Timestamp).HasDefaultValueSql("(sysutcdatetime())");

            entity.HasOne(d => d.Actor).WithMany(p => p.SystemLogs)
                .HasForeignKey(d => d.ActorId)
                .HasConstraintName("FK__SystemLog__Actor__6FE99F9F");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__Users__1788CCACE3CD4A5C");

            entity.HasIndex(e => e.Email, "IX_Users_Email");

            entity.HasIndex(e => e.Role, "IX_Users_Role");

            entity.HasIndex(e => e.Email, "UQ__Users__A9D10534ABECF694").IsUnique();

            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.AvatarUrl)
                .HasMaxLength(500)
                .HasColumnName("AvatarURL");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.DataEncryptionKey).HasMaxLength(500);
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Role)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<UserSubscription>(entity =>
        {
            entity.HasKey(e => e.SubscriptionId).HasName("PK__UserSubs__9A2B24BD668AA507");

            entity.HasIndex(e => new { e.UserId, e.Status }, "IX_UserSubs_User_Status");

            entity.Property(e => e.SubscriptionId).HasColumnName("SubscriptionID");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.PlanId).HasColumnName("PlanID");
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("Active");
            entity.Property(e => e.UsedAnalysisCount).HasDefaultValue(0);
            entity.Property(e => e.UsedTokens).HasDefaultValue(0L);
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Plan).WithMany(p => p.UserSubscriptions)
                .HasForeignKey(d => d.PlanId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__UserSubsc__PlanI__30F848ED");

            entity.HasOne(d => d.User).WithMany(p => p.UserSubscriptions)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__UserSubsc__UserI__300424B4");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}